export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const VIEW_CATEGORIES = "VIEW_CATEGORIES";
export const EDIT_CATEGORIES = "EDIT_CATEGORIES";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const ADD_RECIPE = "ADD_RECIPE";
export const VIEW_RECIPES = "VIEW_RECIPES"